---
- name: Fail if molecule group is missing
  hosts: all
  tasks:
    - name: Install python3 with apt
      ansible.builtin.apt:
        name: python3
        state: present
      become: true

    - name: Include my_web role
      ansible.builtin.include_role:
        name: my_web
      vars:
        ansible_ssh_host: "127.0.0.1"
